### PR TITLE
improved buyWithTokens to check all token types

### PR DESCRIPTION
**Pull request by StormSurge95**
Created an object before the search to hold the number of each token type owned, the npc location for said token type, and the error for each of the three token types. During the search, if we are too far from the required npc, we set the error to say such; or, if we are close enough but don't have enough of said token, we set the error to say such. If we don't find the item during the search, we set the error to say that the item can't be purchased with said token type. At the end, if all three token types have errors, then we throw an AggregateError containing all three errors; otherwise, we proceed using whichever token type had a success.

### CODE REVIEW

**Comment by earthiverse** [comment]
```js
if (tokenTypes.monstertoken.error && tokenTypes.funtoken.error && tokenTypes.pvptoken.error) {
    throw new AggregateError([tokenTypes.monstertoken.error, tokenTypes.funtoken.error, tokenTypes.pvptoken.error])
}
```

I think this error will only be thrown if you have items that are purchasable by all 3 tokens.

**Comment by StormSurge95** [comment]
Hm...it shouldn't be. The error value is set to `null` by default; and then only changed under three conditions:
1) item can't be purchased with that particular token
2) we don't have enough tokens to purchase said item
3) were too far from the npc to purchase from them

**Comment by earthiverse** [comment]
Because of

```js
if (item !== itemName) continue
```

if the item doesn't show up in `tokenTable`, none of the errors will get set for that token, right?

Then, because of the `&&` logic, one will be `null`, and it won't throw?

Or am I wrong?

**Comment by earthiverse** [comment]
I think I'm wrong. The logic below that for loop should set the error

**Comment by StormSurge95** [comment]
After the for loop; it sets the error ONLY if found has not been set. Now that you mention it; if it can be purchased but it fails for some other reason, it will reset the error to say it can't be purchased with tokens.

**Pull request merged**
